package Vistas;

import Modelos.Usuario;
import javax.swing.*;
import java.awt.*;


public class PerfilUsuarioView extends javax.swing.JFrame {

    private Usuario usuario;

    public PerfilUsuarioView(Usuario usuario) {
        this.usuario = usuario;
        initComponents();  // Llama a la inicialización de los componentes
        setTitle("Perfil del Usuario");
        setSize(300, 250);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // Panel con información del usuario
        JPanel panelInfo = new JPanel(new GridLayout(3, 1, 10, 10));
        panelInfo.setBackground(Color.decode("#F1B634")); // Fondo amarillo

        // Verifica que el usuario no sea nulo antes de mostrar sus datos
        if (usuario != null) {
            JLabel lblNombre = new JLabel("Nombre: " + usuario.getNombreCompleto());
            JLabel lblEmail = new JLabel("Correo: " + usuario.getEmail());

            lblNombre.setForeground(Color.decode("#1A1A1A")); // Texto negro
            lblEmail.setForeground(Color.decode("#1A1A1A")); // Texto negro

            panelInfo.add(lblNombre);
            panelInfo.add(lblEmail);
        } else {
            // Si no se recibe un usuario, muestra un mensaje por defecto
            JLabel lblError = new JLabel("Error: Usuario no encontrado.");
            lblError.setForeground(Color.decode("#1A1A1A"));
            panelInfo.add(lblError);
        }

        add(panelInfo, BorderLayout.CENTER);
    }

    private void configurarBoton(JButton boton) {
        boton.setBackground(Color.BLACK); // Fondo negro
        boton.setForeground(Color.WHITE); // Texto blanco
        boton.setFocusPainted(false);
        boton.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Crear y mostrar la forma con un usuario de ejemplo
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Usuario usuario = new Usuario(1, "admin@duoc.cl", "admin123", "Administrador");
                new PerfilUsuarioView(usuario).setVisible(true); // Muestra la vista con un usuario de ejemplo
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
